Shop.WebApp/Controllers/MaterialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WS.Models;
using WS.Repository;
using WS.ViewModels;

namespace WS.WebApp.Controllers
{
    public class MaterialsController : Controller
    {
        private readonly IWorkshopRepository _workshopRepository;
        public MaterialsController(IWorkshopRepository repo)
        {
            _workshopRepository = repo;
        }

        [Authorize(Roles = "User,Manager,Admin")]
        public IActionResult Index()
        {
            List<WSMaterial> materials = _workshopRepository.GetAllMaterials();
            return View(materials);
        }

        [Authorize(Roles = "User,Manager")]
        public IActionResult Create()
        {
            MaterialCreationViewModel model = new MaterialCreationViewModel() { Suppliers = _workshopRepository.GetAllSuppliers() };
            return View(model);
        }

        [Authorize(Roles = "User,Manager")]
        [HttpPost,AutoValidateAntiforgeryToken]
        public IActionResult Create(MaterialCreationViewModel model)
        {
            if (ModelState.IsValid)
            {
                _workshopRepository.CreateMaterial(model.Material);
                return RedirectToAction(nameof(Index));
            }
            model.Suppliers = _workshopRepository.GetAllSuppliers();
            return View(nameof(Create), model);
        }

        [Authorize(Roles = "Manager")]
        public IActionResult Edit(long id)
        {
            WSMaterial material = _workshopRepository.GetMaterial(id);
            List<WSSupplier> suppliers = _workshopRepository.GetAllSuppliers();
            MaterialCreationViewModel model = new MaterialCreationViewModel() { Material = material, Suppliers = suppliers };
            return View(model);
        }

        [Authorize(Roles = "Manager")]
        [HttpPost,AutoValidateAntiforgeryToken]
        public IActionResult Edit(MaterialCreationViewModel model)
        {
            if (ModelState.IsValid)
            {
                _workshopRepository.UpdateMaterial(model.Material);
                return RedirectToAction(nameof(Index));
            }
            MaterialCreationViewModel tempModel = new MaterialCreationViewModel();
            tempModel.Material = model.Material;
            tempModel.Suppliers = _workshopRepository.GetAllSuppliers();
            return View(tempModel);
        }


        [Authorize(Roles = "Manager")]
        public IActionResult Delete(long id)
        {
            WSMaterial temp = _workshopRepository.GetMaterial(id);
            MaterialCreationViewModel model = new MaterialCreationViewModel()
            {
                Material = _workshopRepository.GetMaterial(id),
                Suppliers = new List<WSSupplier> { _workshopRepository.GetMaterialSupplier(id) }
            };
            return View(model);
        }

        [Authorize(Roles = "Manager")]
        [HttpPost,AutoValidateAntiforgeryToken]
        public IActionResult DeleteConfirmed(long id)
        {
            if (ModelState.IsValid)
            {
                _workshopRepository.DeletMaterial(id);
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "User,Manager,Admin")]
        public IActionResult Detailes(long id)
        {
            WSMaterial model = _workshopRepository.GetMaterial(id);
            return View(model);
        }
    }
}

Shop.WebApp/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WS.Interfaces;
using WS.Models.Identity;
using WS.Repository;
using WS.ViewModels;

namespace WS.WebApp.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly IWorkshopRoleRepository _roleManager;
        private readonly IWorkshopUserRepository _userManager;

        public RoleController(IWorkshopRoleRepository roleRepo, IWorkshopUserRepository userRepo)
        {
            _roleManager = roleRepo;
            _userManager = userRepo;
        }

        public async Task<IActionResult> RoleIndex()
        {
            Dictionary<IdentityRole, string> usersInRoles = new Dictionary<IdentityRole, string>();
            foreach(IdentityRole role in _roleManager.Roles)
            {
                string users = String.Join(", ", await _userManager.GetUsersNameInRoleAsync(role.Name));
                usersInRoles.Add(role, users);
            }
            
            return View(usersInRoles);
        }

        public IActionResult CreateRole()
        {
            return View();
        }


        [HttpPost,AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateRole(IdentityRole model)
        {
            if (ModelState.IsValid)
            {
                IdentityResult res = await _roleManager.CreateAsync(model);
                if (res.Succeeded)
                {
                    return RedirectToAction(nameof(RoleIndex));
                }
                foreach(IdentityError error in res.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }


        public async Task<IActionResult> EditRole(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            IEnumerable<User> members = await _userManager.GetUsersInRoleAsync(role.Name);
            IEnumerable<User> nonmembers = await _userManager.GetUsersNotInRoleAsync(role.Name);
            RoleEditViewModel model = new RoleEditViewModel()
            {
                Members = members,
                NonMembers = nonmembers,
                Role = role
            };

            return View(model);
        }


        [HttpPost,AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditRole(string roleid,string userid)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = await _roleManager.FindByIdAsync(roleid);
                User user = await _userManager.FindByIdAsync(userid);
                IdentityResult result;
                if(await _userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await _userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    result = await _userManager.AddToRoleAsync(user, role.Name);
                }

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(EditRole),new { id = role.Id });
                }
                foreach(IdentityError error in result.Errors)
                {
                    ModelState.AddModelError(error.Code, error.Description);
                }
            }
            IdentityRole role1 = await _roleManager.FindByIdAsync(roleid);
            IEnumerable<User> members = await _userManager.GetUsersInRoleAsync(role1.Name);
            RoleEditViewModel model = new RoleEditViewModel()
            {
                Members = members,
                NonMembers = _userManager.Users.Except(members),
                Role = role1
            };

            return View(model);
        }

        [HttpPost,AutoValidateAntiforgeryToken]
        public async Task<IActionResult> DeleteRole(string id)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = await _roleManager.FindByIdAsync(id);
                IdentityResult result = await _roleManager.DeleteAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(RoleIndex));
                }
                foreach(IdentityError error in result.Errors)
                {
                    ModelState.AddModelError(error.Code, error.Description);
                }
            }

            Dictionary<IdentityRole, string> usersInRoles = new Dictionary<IdentityRole, string>();
            foreach (IdentityRole role in _roleManager.Roles)
            {
                string users = String.Join(", ", await _userManager.GetUsersNameInRoleAsync(role.Name));
                usersInRoles.Add(role, users);
            }

            return View(nameof(RoleIndex),usersInRoles);

        }
    }
}

Shop.WebApp/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WS.Interfaces;
using WS.Models.Identity;
using WS.Repository;
using WS.ViewModels;
using WS.ExtraFunctions;


namespace WS.WebApp.Controllers
{
    [Authorize(Roles ="Admin")]
    public class UserController : Controller
    {
        private readonly IWorkshopUserRepository _userManager;
        private readonly IWorkshopRoleRepository _roleManager;

        public UserController(IWorkshopUserRepository userManager, IWorkshopRoleRepository roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult UserIndex()
        {
            IEnumerable<User> users = _userManager.Users;
            return View(users);
        }

        public IActionResult CreateUser()
        {
            return View();
        }


        [HttpPost,AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateUser(User model)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await _userManager.CreateAsync(model, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(UserIndex));
                }
                foreach(IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);

        }


        public async Task<IActionResult> EditUser(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            IEnumerable<string> allRoles = _roleManager.GetAllRoles();
            IList<string> userRoles = await _userManager.GetRolesAsync(user);
            Dictionary<string, bool> dictionary = new Dictionary<string, bool>();
            foreach(string role in allRoles)
            {
                if (userRoles.Contains(role))
                {
                    dictionary.Add(role, true);
                }
                else
                {
                    dictionary.Add(role, false);
                }
            }
            EditUserViewModel model = new EditUserViewModel
            {
                Email = user.Email,
                FirstName = user.FirstName,
                Id = user.Id,
                LastName = user.LastName,
                Status = user.Status,
                UserName = user.UserName,
                Roles = dictionary
            };
            return View(model);
        }


        [HttpPost,AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);

                IEnumerable<string> roles = _roleManager.GetAllRoles();
                foreach (string role in roles)
                {
                    await _userManager.RemoveFromRoleAsync(user, role);
                }

                if (model.Roles != null)
                {
                    foreach(KeyValuePair<string,bool> role in model.Roles)
                    {
                        await _userManager.AddToRoleAsync(user, role.Key);
                    }
                }

                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.UserName = model.UserName;
                user.Email = model.Email;
                //user.Status = model.Status;
                user.NormalizedEmail = user.Email.ToUpper();
                user.NormalizedUserName = user.UserName.ToUpper();


                IdentityResult result = await _userManager.UpdateUserAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(UserIndex));
                }
                foreach(IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            User tempUser = await _userManager.FindByIdAsync(model.Id);
            IEnumerable<string> allRoles = _roleManager.GetAllRoles();
            IList<string> userRoles = await _userManager.GetRolesAsync(tempUser);
            Dictionary<string, bool> dictionary = new Dictionary<string, bool>();
            foreach (string role in allRoles)
            {
                if (userRoles.Contains(role))
                {
                    dictionary.Add(role, true);
                }
                else
                {
                    dictionary.Add(role, false);
                }
            }
            model.Roles = dictionary;
            return View(model);
        }


        
        [HttpPost,AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(string id)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(id);
                IEnumerable<string> roles = _roleManager.GetAllRoles();
                foreach(string role in roles)
                {
                    await _userManager.RemoveFromRoleAsync(user, role);
                }
                
                int delResult = await _userManager.DeleteUser(id);
                
            }
            return RedirectToAction(nameof(UserIndex));
        }


        [HttpPost, AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Recover(string id)
        {
            if (ModelState.IsValid)
            {
                int delResult = await _userManager.RecoverUserById(id);
            }
            return RedirectToAction(nameof(UserIndex));
        }


        [HttpPost,AutoValidateAntiforgeryToken]
        public async Task<IActionResult> ResetPassword(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                string newPassword = Utilities.PasswordGenerator();
                User user = await _userManager.FindByIdAsync(model.Id);

                await _userManager.RemovePasswordAsync(user);
                IdentityResult result = await _userManager.AddPasswordAsync(user, newPassword);
                //IdentityResult result = await _userManager.UpdatePasswordHash(user, newPassword, true);
                if (result.Succeeded)
                {
                    //we should add a mail service to send an email to the user and inform about the new generated password.
                    TempData["newPassword"] = newPassword;
                    TempData["UserId"] = user.Id;
                    return RedirectToAction(nameof(PasswordResetedNotification));
                }
                foreach(IdentityError error in result.Errors)
                {
                    ModelState.AddModelError(error.Code, error.Description);
                }
            }
            return View(model);
        }


        public async Task<IActionResult> PasswordResetedNotification()
        {

            string Id = ((Guid)TempData["UserId"]).ToString();
            User user = await _userManager.FindByIdAsync(Id);
            string password = (string)TempData["newPassword"];

            PasswordResetViewModel model = new PasswordResetViewModel
            {
                Email = user.Email,
                Password = password,
                UserName = user.UserName
            };
            
            return View(model);
        }
    }
}

Shop.WebApp/Views/Shared/AccessDenied.cshtml
@{ Layout = null;}
<!DOCTYPE html>

<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet"
              asp-href-include="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css"
              asp-fallback-test-class="progress"
              asp-fallback-test-property="display"
              asp-fallback-test-value="flex"
              asp-fallback-href="~/twitter-bootstrap/css/bootstrap.min.css" />

        <title>Access Denied</title>
    </head>
    <body>
        <h4 class="bg-danger text-white text-center p-2">Access Denied</h4>
        <div class="m-2">
            <h6>You are not authorized for this URL</h6>
            <a class="btn btn-outline-danger" href="/">OK</a>
        </div>
    </body>
</html>

Shop.WebApp/Views/Shared/_IdentityLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet"
          asp-href-include="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css"
          asp-fallback-test-class="progress"
          asp-fallback-test-property="display"
          asp-fallback-test-value="flex"
          asp-fallback-href="~/twitter-bootstrap/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Admin" asp-action="@nameof(WS.WebApp.Controllers.AdminController.AdminIndex)">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="User" asp-action="@nameof(WS.WebApp.Controllers.UserController.UserIndex)">Users</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Role" asp-action="@nameof(WS.WebApp.Controllers.RoleController.RoleIndex)">Roles</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="SignOut">Log Out</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div>
        <h5 class="bg-info text-white text-center p-2">Administration</h5>
        @RenderBody()
    </div>
</body>
</html>

Shop.WebApp/Views/Shared/_Layout.cshtml
@inject IViewLocalizer Localizer
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" 
          asp-href-include="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css"
          asp-fallback-test-class="progress"
          asp-fallback-test-property="display"
          asp-fallback-test-value="flex"
          asp-fallback-href="~/twitter-bootstrap/css/bootstrap.min.css" /> 
    <link href="~/hand_tool_tools_work_building_repair_construction_construction_tools-91_icon-icons.com_60418.ico" type="image/x-icon" rel="shortcut icon" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Products" asp-action="Index">@Localizer["Products"]</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Suppliers" asp-action="Index">@Localizer["Suppliers"]</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Materials" asp-action="Index">@Localizer["Materials"]</a>
                </li>

                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="SignOut">@Localizer["Log Out"]</a>

                    </li>
                    <li class="nav-item">
                        <span class="navbar-text" style="color:mediumblue">@User.Identity.Name</span>
                    </li>
                    <li class="disabled">
                        &emsp;&emsp;
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="ChangePassword" class="nav-link">@Localizer["Change Password"]</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Login" asp-route-returnUrl="@string.Format("{0}://{1}{2}{3}", Context.Request.Scheme, Context.Request.Host, Context.Request.Path, Context.Request.QueryString)">@Localizer["Log In"]</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="CreateUser">@Localizer["Register"]</a>
                    </li>
                }

                <li class="nav-item">
                    <form id="langForm" asp-controller="Home" asp-action="SetLanguage" method="post">
                        <input hidden name="returnUrl" value="@(string.IsNullOrEmpty(Context.Request.Path)?"~/": Context.Request.Path.Value)" />
                        <select name="culture" class="dropdown m-2">
                            @switch (Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>().RequestCulture.UICulture.Name)
                            {
                                case "hy":
                                    <option selected value="@("hy")">Armenian(Հայերեն)</option>
                                    <option value="@("en")">English</option>
                                    break;
                                default:
                                    <option value="@("hy")">Armenian(Հայերեն)</option>
                                    <option selected value="@("en")">English</option>
                                    break;
                            }
                        </select>
                    </form>
                </li>
                <li class="nav-item">
                    <button form="langForm" type="submit" class="btn-sm btn-light">@Localizer["Submit Language"]</button>
                </li>
            </ul>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
</body>
</html>