Shop.WebApp/Controllers/SuppliersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WS.Data;
using WS.Models;
using WS.Repository;

namespace WS.WebApp.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly IWorkshopRepository _workshopRepository;
        

        public SuppliersController(IWorkshopRepository repository)
        {
            _workshopRepository = repository;
        }

        [Authorize(Roles ="User,Manager,Admin")]
        public IActionResult Index()
        {
            var result = _workshopRepository.GetAllSuppliers();
            return View(result);
        }

        [Authorize(Roles = "User,Manager")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "User,Manager")]
        [HttpPost,AutoValidateAntiforgeryToken]
        public IActionResult Create(WSSupplier model)
        {
            int result = -1;
            if (ModelState.IsValid)
            {
                result = _workshopRepository.CreateSupplier(model);
            }

            if(result > 0)
            {
                TempData["ViewMessage"] = "Supplier Created";
            }
            else
            {
                TempData["ViewMessage"] = "Supplier NOT Created";
            }

            return RedirectToAction(nameof(Index));
        }


        [Authorize(Roles = "Manager")]
        public IActionResult EditSupplier(long id)
        {
            WSSupplier result = _workshopRepository.GetSupplier(id);
            return View(result);
        }


        [Authorize(Roles = "Manager")]
        [HttpPost,AutoValidateAntiforgeryToken]
        public IActionResult EditSupplier(WSSupplier model)
        {
            if (ModelState.IsValid)
            {
                _workshopRepository.UpdateSupplier(model);
            }
            TempData["ViewMessage"] = "Supplier is modified";
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Manager")]
        public IActionResult DeleteSupplier(long id)
        {
            WSSupplier result = _workshopRepository.GetSupplier(id);
            return View(result);
        }

        [Authorize(Roles = "Manager")]
        [HttpPost,AutoValidateAntiforgeryToken]
        public IActionResult DeleteSupplierConfirm(long id)
        {
            if (ModelState.IsValid)
            {
                _workshopRepository.DeleteSupplier(id);
            }

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "User,Manager,Admin")]
        public IActionResult DetailSupplier(long id)
        {
            WSSupplier result = _workshopRepository.GetSupplier(id);
            return View(result);
        }
    }
}

Shop.WebApp/Views/Suppliers/Create.cshtml
@model WSSupplier

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>WSSupplier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SupplierName" class="control-label"></label>
                <input asp-for="SupplierName" class="form-control" />
                <span asp-validation-for="SupplierName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Shop.WebApp/Views/Suppliers/DeleteSupplier.cshtml
@model WSSupplier

@{
    ViewData["Title"] = "DeleteSupplier";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>DeleteSupplier</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WSSupplier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SupplierName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>
    
    <form asp-action="DeleteSupplierConfirm">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Shop.WebApp/Views/Suppliers/DetailSupplier.cshtml
@model WS.Models.WSSupplier

@{
    ViewData["Title"] = "DetailSupplier";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>DetailSupplier</h1>

<div>
    <h4>WSSupplier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SupplierName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contact)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contact)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="EditSupplier" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Shop.WebApp/Views/Suppliers/EditSupplier.cshtml
@model WSSupplier

@{
    ViewData["Title"] = "EditSupplier";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>EditSupplier</h1>

<h4>WSSupplier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditSupplier" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" class="form-control" hidden />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierName" class="control-label"></label>
                <input asp-for="SupplierName" class="form-control" />
                <span asp-validation-for="SupplierName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contact" class="control-label"></label>
                <input asp-for="Contact" class="form-control" />
                <span asp-validation-for="Contact" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-warning" /> |
                <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
</div>

Shop.WebApp/Views/Suppliers/Index.cshtml
@model List<WSSupplier>

<a asp-controller="Suppliers" asp-action="Create" class="btn btn-primary">Create</a> 
<span>@TempData["ViewMessage"]</span>

<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Contact
            </th>
            <th>
                Address
            </th>
            <th>
                Options
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(WSSupplier s in Model)
        {
            <tr>
                <td>@s.Id</td>
            
                <td>@s.SupplierName</td>
                
                <td>@s.Contact</td>
                <td>@s.Address</td>
                <td>
                    <a asp-controller="Suppliers" asp-action="EditSupplier" asp-route-id="@s.Id" class="btn btn-warning">Edit</a>
                    <a asp-controller="Suppliers" asp-action="DeleteSupplier" asp-route-id="@s.Id" class="btn btn-danger">Delete</a>
                    <a asp-controller="Suppliers" asp-action="DetailSupplier" asp-route-id="@s.Id" class="btn btn-secondary">Detailes</a>
                </td>
            </tr>
        }
    </tbody>
</table>